# -*- coding: utf-8 -*-
"""CareerAdvisor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PloZuD-2mBSArD09AhSXDUDI8By3wJkU
"""

!apt-get update -qq
!apt-get install -y zstd

!curl -fsSL https://ollama.com/install.sh | sh

import subprocess
import time

# Start Ollama server as a background process
process = subprocess.Popen(["ollama", "serve"])
time.sleep(5)  
print("Ollama server started.")

!ollama pull phi3

!pip install ollama

"""
Domain-Specific Chatbot using Ollama — Google Colab version
Domain: Career Advisor

"""

import ollama

MODEL_NAME = "phi3"

SYSTEM_PROMPT = """You are CareerBot, a professional and friendly Career Advisor assistant.

Your job is to help users with:
- Resume and CV advice
- Job search strategies
- Interview preparation
- Career path guidance
- Skill development recommendations
- Workplace and professional development questions

STRICT RULES:
1. Only answer questions related to careers, jobs, resumes, interviews, and
   professional development.
2. If a user asks something unrelated to careers (e.g. medical advice, coding
   help unrelated to careers, general trivia, math problems, etc.), politely
   decline and redirect them back to career-related topics. Say something like:
   "I'm a Career Advisor assistant, so I can only help with career-related
   questions. Could you ask me something about your job search, resume, or
   career path instead?"
3. Keep answers concise, practical, and encouraging.
4. Never pretend to be a doctor, lawyer, or any other type of professional.
"""

def build_chatbot():
    return [{"role": "system", "content": SYSTEM_PROMPT}]


def chat():
    conversation = build_chatbot()

    print("=" * 60)
    print(" CareerBot - Your AI Career Advisor")
    print(" Type 'exit' or 'quit' to end the conversation.")
    print("=" * 60)

    while True:
        user_input = input("\nYou: ").strip()

        if user_input.lower() in ["exit", "quit"]:
            print("CareerBot: Good luck with your career journey! Goodbye.")
            break

        if not user_input:
            continue

        conversation.append({"role": "user", "content": user_input})

        response = ollama.chat(
            model=MODEL_NAME,
            messages=conversation
        )

        reply = response["message"]["content"]
        print(f"\nCareerBot: {reply}")

        conversation.append({"role": "assistant", "content": reply})


chat()