# -*- coding: utf-8 -*-
"""Sentiment_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5oOmS0crduVLfEdZV1CG_sqRflMEIVg

I'm taking help from recorded sessions and AI but i'm learning.
"""

import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

#Choosing Dataset (Through link bcz it was complex through file in colab)
url = "https://raw.githubusercontent.com/Giskard-AI/examples/main/datasets/twitter_us_airline_sentiment_analysis.csv"
df = pd.read_csv(url)

# columns we actually need
df = df[['text', 'airline_sentiment']]
df.columns = ['text', 'sentiment']

print(df.shape)
df.head()

df['sentiment'].value_counts()

#PreProcessing Text
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words] # remove stopwords
    return ' '.join(words)

df['clean_text'] = df['text'].apply(clean_text)
df[['text', 'clean_text']].head()

#Splitting into Training and Testing
X = df['clean_text']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

#Conerting into numbers
vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print(X_train_tfidf.shape)

#Classification Model
# Logistic Regression
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_tfidf, y_train)

# Naive Bayes
nb_model = MultinomialNB()
nb_model.fit(X_train_tfidf, y_train)

print("Both models trained!")

#Don't really understand the functions
for name, model in [("Logistic Regression", log_model), ("Naive Bayes", nb_model)]:
    preds = model.predict(X_test_tfidf)
    acc = accuracy_score(y_test, preds)
    print(f"\n{'='*50}")
    print(f"{name} — Accuracy: {acc:.4f}")
    print(f"{'='*50}")
    print(classification_report(y_test, preds))

sample_tweets = [
    "This airline is amazing, best flight ever!",
    "Worst experience, my flight got delayed for 5 hours",
    "The flight was okay, nothing special"
]

sample_clean = [clean_text(t) for t in sample_tweets]
sample_tfidf = vectorizer.transform(sample_clean)

predictions = log_model.predict(sample_tfidf)

for tweet, pred in zip(sample_tweets, predictions):
    print(f"'{tweet}' → {pred}")

