# -*- coding: utf-8 -*-
"""Text_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYZhPJGNFb_9047s4Nh7dg2FQlcQ0Ew2
"""

!pip install scikit-learn seaborn matplotlib

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# STEP 1: Map newsgroup categories to labels
CATEGORY_MAP = {
    "comp.graphics": "Technology",
    "comp.sys.ibm.pc.hardware": "Technology",
    "comp.windows.x": "Technology",
    "rec.sport.baseball": "Sports",
    "rec.sport.hockey": "Sports",
    "sci.space": "Education",
    "sci.med": "Education",
    "misc.forsale": "Business",
}
newsgroup_names = list(CATEGORY_MAP.keys())


# STEP 2: Load dataset
dataset = fetch_20newsgroups(
    subset="all",
    categories=newsgroup_names,
    remove=("headers", "footers", "quotes"),
)
print("Total documents with their length:", len(dataset.data))
print("Total categories:", len(dataset.target_names))
print("Categories:", dataset.target_names)
X = dataset.data
y_raw = dataset.target  # numeric ids pointing into dataset.target_names

# Convert numeric target -> newsgroup name -> simplified labels
y = [CATEGORY_MAP[dataset.target_names[i]] for i in y_raw]


# STEP 3: Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))


# STEP 4: Convert text -> TF-IDF
vectorizer = TfidfVectorizer(stop_words="english", max_df=0.7)

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)
print("TF-IDF matrix shape:", X_train_tfidf.shape)


# STEP 5: Train the model
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)
print("Model trained successfully.")


# STEP 6: Evaluate the model
y_pred = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.2f}")
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


# STEP 7: Confusion matrix
labels = sorted(set(y))
cm = confusion_matrix(y_test, y_pred, labels=labels)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()


# STEP 8: continuous input loop.
def classify(text):
    text_tfidf = vectorizer.transform([text])
    prediction = model.predict(text_tfidf)[0]
    return prediction


def main():
    print("\n" + "=" * 50)
    print("TEXT CLASSIFICATION SYSTEM")
    print("Categories: Technology, Sports, Education, Business")
    print("Type 'quit' or 'exit' to stop.")
    print("=" * 50)

    while True:
        user_text = input("\nEnter text to classify: ").strip()

        if user_text.lower() in ("quit", "exit"):
            print("Goodbye!")
            break

        if not user_text:
            print("Please enter some text.")
            continue

        category = classify(user_text)
        print(f"Category: {category}")


if __name__ == "__main__":
    main()